### ISSUE TITLE
[Imrpovement] Engine security filter

### ISSUE THREAD

**Issue by guillain** [bernard357/shellbot#37]
Add email list in the engine to valid the bot access/usage.

**Comment by bernard357** [comment]
Guillain, can you refine a bit on this requirement please? What is the view of this, from edn user perspective? Thanks

**Comment by guillain** [comment]
Hi Bernard,

Effectively my explanation was too short :/

The idea is to put in place the access list on the participant level.
Shellbot should have the capability to manage the participant permission (privilege) to interact with the bot.

According to my sketch, it's what I did in the MachineFactory class during the get_machine.
The participant is allowed if the bot.space.list_participants contains the mail of someone in the YAML file used to set the team members. 

On Shellbot side I think this can be integrated in the settings, ie:
participant:

```
participants:
    allowed:
        - toto@test.com
        - tata@test.com
    blocked:
        - tutu@test.com
        - titi@test.com
```

After that some specific features can be integrated when we overload this class to provide specific privileges (ie only group or 1:1... but don't find solution for the RW vs RO without deleting the posted message :/ if you have an idea :) )

Thanks!
